---
kind: pipeline
type: kubernetes
name: default

steps:
  - name: build
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run/
    commands:
      - docker build --tag dijitle/snake:$DRONE_COMMIT .
  - name: push
    image: docker:dind
    privileged: true
    environment:
      USERNAME:
        from_secret: docker_username
      PASSWORD:
        from_secret: docker_password
    volumes:
      - name: dockersock
        path: /var/run/
    commands:
      - docker tag dijitle/snake:$DRONE_COMMIT dijitle/snake:$DRONE_TAG
      - docker login -u $USERNAME -p $PASSWORD
      - docker push dijitle/snake:$DRONE_TAG
    when:
      event:
        - tag
  - name: deploy
    image: dijitle/kubectl:v1.17.2
    environment:
      KUBERNETES_CERT:
        from_secret: k8s_cert
      KUBERNETES_TOKEN:
        from_secret: k8s_token
    commands:
      - kubectl-init.sh
      - kubectl set image deployment/snake-deployment snake=dijitle/snake:$DRONE_TAG
    when:
      event:
        - tag
volumes:
  - name: dockersock
    host:
      path: /var/run/
---
kind: signature
hmac: e1fda1c0769e5fa4b61dda603da375f8a966129ab58436308ae4c303ecfe41fd
